### ISSUE TITLE
kontena-ipam-cleanup is not safe against concurrent IpamDriver.RequestAddress

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena-ipam#53]
* Only delete etcd nodes older than e.g. 5 minutes during cleanup, to avoid conflicts with ongoing allocations.

**Comment by jnummelin** [comment]
@SpComb Would you be able to whip up a fix for this so we can enable the cleanup on agent side.

**Comment by SpComb** [comment]
Doesn't seem like etcd has any native node timestamps.

Two options:

## Three-stage cleanup

* Probe current etcd index
* List currently active networks
* Clean nodes with a createdIndex earlier than the probed etcd index

## Timestamp nodes ourselves

Add a new `allocated_at` timestamp field to the etcd `/kontena/ipam/addresses/:pool/:id` nodes.

**Comment by SpComb** [comment]
There's may still be a race condition present with the three-stage cleanup scheme, because the `docker create ...` `IpamDriver.RequestAddress` operation is not necessarily atomic with respect to `docker network inspect`? It can take a considerable amount of time between the `IpamDriver.RequestAddress` operation completing and the new container showing up in the Docker API.

* Docker starts IPAM RequestAddress -> etcd set `/kontena/ipam/addresses/pool/A` @ etcd-index X
* Cleanup starts with etcd-index = X
* Cleanup gets addresses from Docker API network endpoints, but does not yet see the endpoint with address=A
* Docker completes and the endpoint with address=A shows up in the Docker API.
* Cleanup happens with etcd-index=X, without knowing about the allocated address A
* Cleanup releases the in-use address=A at etcd-index=X
